server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: CART-APPLICATION
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**
        - id: SHOP
          uri: lb://SHOP
          predicates:
            - Path=/products/**

